Update terraform.yml

diff --git a/.github/workflows/terraform.yml b/.github/workflows/terraform.yml
--- a/.github/workflows/terraform.yml
+++ b/.github/workflows/terraform.yml
@@ -87,7 +87,7 @@ jobs:
           ${TARGET_ENV}/**/*.out
           ${TARGET_ENV}/**/*.hcl
         
-  terraform_apply:
+terraform_apply:
     runs-on: ubuntu-latest
     if: github.ref == 'refs/heads/main'  # Trigger on pushes to main branch
 
@@ -100,7 +100,6 @@ jobs:
       with:
         name: terraform-artifacts
         path: main
-        
 
     - name: List files in $TARGET_ENV directory
       run: |
@@ -117,20 +116,23 @@ jobs:
       with:
         credentials_json: ${{ secrets.GCP_SA_KEY }}
 
-    - name: Terraform Init and Apply
+    - name: Terraform Apply
+      shell: bash
       run: |
-        echo "Applying Terraform in $TARGET_ENV environment."
-        
+        echo "Applying Terraform Plan"
         if [ -d "${TARGET_ENV}/" ]; then
           for dir in ${TARGET_ENV}/*/; do
             if [ -d "$dir" ]; then
               cd $dir
               env=$(basename "$dir")
               
-              echo "*************** TERRAFORM APPLY in $dir ******************"
-              
-              # Ensure the correct path to the plan file
-              terraform apply -auto-approve "tfplan-${env}.out" || exit 1
+              # Check if the Terraform plan file exists
+              if [ -f "tfplan-${env}.out" ]; then
+                echo "*************** APPLYING PLAN in $dir ******************"
+                terraform apply "tfplan-${env}.out" || exit 1
+              else
+                echo "Plan file tfplan-${env}.out not found in $dir"
+              fi
               
               cd - > /dev/null
             fi
@@ -139,4 +141,3 @@ jobs:
           echo "Directory '${TARGET_ENV}' does not exist."
           exit 1
         fi
-
